apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- target:
    kind: Service
    name: appsmith
  patch: |-
    - op: add
      path: /metadata/labels/custom.teleport.kubernetes-discovery
      value: "non-engineer"